// AUTO-GENERATED from spec. Do not edit; run aolib-gen.
#include "aolib/registry_gen.hpp"

#include "aolib/packets_gen.hpp"
#include "aolib/wire.hpp"

namespace aolib {

const std::map<std::string, FantaDecoder> c2s_decoders = {
    {"CASEA", [](const std::vector<std::string>& b) { auto p = CASEAToServer::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"CC", [](const std::vector<std::string>& b) { auto p = CC::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"CH", [](const std::vector<std::string>& b) { auto p = CH::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"CT", [](const std::vector<std::string>& b) { auto p = CTToServer::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"DE", [](const std::vector<std::string>& b) { auto p = DE::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"EE", [](const std::vector<std::string>& b) { auto p = EE::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"HI", [](const std::vector<std::string>& b) { auto p = HI::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"HP", [](const std::vector<std::string>& b) { auto p = HPToServer::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"ID", [](const std::vector<std::string>& b) { auto p = IDToServer::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"MA", [](const std::vector<std::string>& b) { auto p = MA::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"MC", [](const std::vector<std::string>& b) { auto p = MCToServer::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"MS", [](const std::vector<std::string>& b) { auto p = MSToServer::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"PE", [](const std::vector<std::string>& b) { auto p = PE::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"RC", [](const std::vector<std::string>& b) { auto p = RC::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"RD", [](const std::vector<std::string>& b) { auto p = RD::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"RM", [](const std::vector<std::string>& b) { auto p = RM::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"RT", [](const std::vector<std::string>& b) { auto p = RTToServer::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"SETCASE", [](const std::vector<std::string>& b) { auto p = SETCASE::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"ZZ", [](const std::vector<std::string>& b) { auto p = ZZToServer::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"askchaa", [](const std::vector<std::string>& b) { auto p = askchaa::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
};

const std::map<std::string, FantaDecoder> s2c_decoders = {
    {"ARUP", [](const std::vector<std::string>& b) { auto p = ARUP::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"ASS", [](const std::vector<std::string>& b) { auto p = ASS::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"AUTH", [](const std::vector<std::string>& b) { auto p = AUTH::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"BB", [](const std::vector<std::string>& b) { auto p = BB::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"BD", [](const std::vector<std::string>& b) { auto p = BD::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"BN", [](const std::vector<std::string>& b) { auto p = BN::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"CASEA", [](const std::vector<std::string>& b) { auto p = CASEAToClient::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"CHECK", [](const std::vector<std::string>& b) { auto p = CHECK::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"CI", [](const std::vector<std::string>& b) { auto p = CI::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"CT", [](const std::vector<std::string>& b) { auto p = CTToClient::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"CharsCheck", [](const std::vector<std::string>& b) { auto p = CharsCheck::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"DONE", [](const std::vector<std::string>& b) { auto p = DONE::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"EI", [](const std::vector<std::string>& b) { auto p = EI::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"EM", [](const std::vector<std::string>& b) { auto p = EM::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"FA", [](const std::vector<std::string>& b) { auto p = FA::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"FL", [](const std::vector<std::string>& b) { auto p = FL::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"FM", [](const std::vector<std::string>& b) { auto p = FM::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"HP", [](const std::vector<std::string>& b) { auto p = HPToClient::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"ID", [](const std::vector<std::string>& b) { auto p = IDToClient::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"JD", [](const std::vector<std::string>& b) { auto p = JD::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"KB", [](const std::vector<std::string>& b) { auto p = KB::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"KK", [](const std::vector<std::string>& b) { auto p = KK::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"LE", [](const std::vector<std::string>& b) { auto p = LE::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"MC", [](const std::vector<std::string>& b) { auto p = MCToClient::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"MS", [](const std::vector<std::string>& b) { auto p = MSToClient::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"PN", [](const std::vector<std::string>& b) { auto p = PN::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"PR", [](const std::vector<std::string>& b) { auto p = PR::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"PU", [](const std::vector<std::string>& b) { auto p = PU::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"PV", [](const std::vector<std::string>& b) { auto p = PV::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"RMC", [](const std::vector<std::string>& b) { auto p = RMC::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"RT", [](const std::vector<std::string>& b) { auto p = RTToClient::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"SC", [](const std::vector<std::string>& b) { auto p = SC::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"SI", [](const std::vector<std::string>& b) { auto p = SI::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"SM", [](const std::vector<std::string>& b) { auto p = SM::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"SP", [](const std::vector<std::string>& b) { auto p = SP::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"ST", [](const std::vector<std::string>& b) { auto p = ST::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"TI", [](const std::vector<std::string>& b) { auto p = TI::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"ZZ", [](const std::vector<std::string>& b) { auto p = ZZToClient::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
    {"decryptor", [](const std::vector<std::string>& b) { auto p = decryptor::parse(b); validate_packet(p); return std::any{std::move(p)}; }},
};

const std::map<std::string, JsonDecoder> c2s_json = {
    {"CASEA", [](const std::string& raw) { CASEAToServer p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"CC", [](const std::string& raw) { CC p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"CH", [](const std::string& raw) { CH p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"CT", [](const std::string& raw) { CTToServer p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"DE", [](const std::string& raw) { DE p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"EE", [](const std::string& raw) { EE p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"HI", [](const std::string& raw) { HI p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"HP", [](const std::string& raw) { HPToServer p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"ID", [](const std::string& raw) { IDToServer p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"MA", [](const std::string& raw) { MA p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"MC", [](const std::string& raw) { MCToServer p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"MS", [](const std::string& raw) { MSToServer p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"PE", [](const std::string& raw) { PE p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"RC", [](const std::string& raw) { RC p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"RD", [](const std::string& raw) { RD p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"RM", [](const std::string& raw) { RM p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"RT", [](const std::string& raw) { RTToServer p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"SETCASE", [](const std::string& raw) { SETCASE p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"ZZ", [](const std::string& raw) { ZZToServer p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"askchaa", [](const std::string& raw) { askchaa p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
};

const std::map<std::string, JsonDecoder> s2c_json = {
    {"ARUP", [](const std::string& raw) { ARUP p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"ASS", [](const std::string& raw) { ASS p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"AUTH", [](const std::string& raw) { AUTH p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"BB", [](const std::string& raw) { BB p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"BD", [](const std::string& raw) { BD p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"BN", [](const std::string& raw) { BN p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"CASEA", [](const std::string& raw) { CASEAToClient p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"CHECK", [](const std::string& raw) { CHECK p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"CI", [](const std::string& raw) { CI p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"CT", [](const std::string& raw) { CTToClient p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"CharsCheck", [](const std::string& raw) { CharsCheck p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"DONE", [](const std::string& raw) { DONE p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"EI", [](const std::string& raw) { EI p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"EM", [](const std::string& raw) { EM p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"FA", [](const std::string& raw) { FA p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"FL", [](const std::string& raw) { FL p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"FM", [](const std::string& raw) { FM p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"HP", [](const std::string& raw) { HPToClient p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"ID", [](const std::string& raw) { IDToClient p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"JD", [](const std::string& raw) { JD p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"KB", [](const std::string& raw) { KB p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"KK", [](const std::string& raw) { KK p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"LE", [](const std::string& raw) { LE p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"MC", [](const std::string& raw) { MCToClient p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"MS", [](const std::string& raw) { MSToClient p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"PN", [](const std::string& raw) { PN p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"PR", [](const std::string& raw) { PR p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"PU", [](const std::string& raw) { PU p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"PV", [](const std::string& raw) { PV p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"RMC", [](const std::string& raw) { RMC p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"RT", [](const std::string& raw) { RTToClient p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"SC", [](const std::string& raw) { SC p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"SI", [](const std::string& raw) { SI p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"SM", [](const std::string& raw) { SM p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"SP", [](const std::string& raw) { SP p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"ST", [](const std::string& raw) { ST p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"TI", [](const std::string& raw) { TI p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"ZZ", [](const std::string& raw) { ZZToClient p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
    {"decryptor", [](const std::string& raw) { decryptor p; decode_json_into(p, raw); return std::any{std::move(p)}; }},
};

const std::map<std::string, PacketConstructor> packet_constructors = {
    {"ARUP", []() { return std::any{ARUP{}}; }},
    {"ASS", []() { return std::any{ASS{}}; }},
    {"AUTH", []() { return std::any{AUTH{}}; }},
    {"BB", []() { return std::any{BB{}}; }},
    {"BD", []() { return std::any{BD{}}; }},
    {"BN", []() { return std::any{BN{}}; }},
    {"CASEAToClient", []() { return std::any{CASEAToClient{}}; }},
    {"CASEAToServer", []() { return std::any{CASEAToServer{}}; }},
    {"CC", []() { return std::any{CC{}}; }},
    {"CH", []() { return std::any{CH{}}; }},
    {"CHECK", []() { return std::any{CHECK{}}; }},
    {"CI", []() { return std::any{CI{}}; }},
    {"CTToClient", []() { return std::any{CTToClient{}}; }},
    {"CTToServer", []() { return std::any{CTToServer{}}; }},
    {"CharsCheck", []() { return std::any{CharsCheck{}}; }},
    {"DE", []() { return std::any{DE{}}; }},
    {"DONE", []() { return std::any{DONE{}}; }},
    {"EE", []() { return std::any{EE{}}; }},
    {"EI", []() { return std::any{EI{}}; }},
    {"EM", []() { return std::any{EM{}}; }},
    {"FA", []() { return std::any{FA{}}; }},
    {"FL", []() { return std::any{FL{}}; }},
    {"FM", []() { return std::any{FM{}}; }},
    {"HI", []() { return std::any{HI{}}; }},
    {"HPToClient", []() { return std::any{HPToClient{}}; }},
    {"HPToServer", []() { return std::any{HPToServer{}}; }},
    {"IDToClient", []() { return std::any{IDToClient{}}; }},
    {"IDToServer", []() { return std::any{IDToServer{}}; }},
    {"JD", []() { return std::any{JD{}}; }},
    {"KB", []() { return std::any{KB{}}; }},
    {"KK", []() { return std::any{KK{}}; }},
    {"LE", []() { return std::any{LE{}}; }},
    {"MA", []() { return std::any{MA{}}; }},
    {"MCToClient", []() { return std::any{MCToClient{}}; }},
    {"MCToServer", []() { return std::any{MCToServer{}}; }},
    {"MSToClient", []() { return std::any{MSToClient{}}; }},
    {"MSToServer", []() { return std::any{MSToServer{}}; }},
    {"PE", []() { return std::any{PE{}}; }},
    {"PN", []() { return std::any{PN{}}; }},
    {"PR", []() { return std::any{PR{}}; }},
    {"PU", []() { return std::any{PU{}}; }},
    {"PV", []() { return std::any{PV{}}; }},
    {"RC", []() { return std::any{RC{}}; }},
    {"RD", []() { return std::any{RD{}}; }},
    {"RM", []() { return std::any{RM{}}; }},
    {"RMC", []() { return std::any{RMC{}}; }},
    {"RTToClient", []() { return std::any{RTToClient{}}; }},
    {"RTToServer", []() { return std::any{RTToServer{}}; }},
    {"SC", []() { return std::any{SC{}}; }},
    {"SETCASE", []() { return std::any{SETCASE{}}; }},
    {"SI", []() { return std::any{SI{}}; }},
    {"SM", []() { return std::any{SM{}}; }},
    {"SP", []() { return std::any{SP{}}; }},
    {"ST", []() { return std::any{ST{}}; }},
    {"TI", []() { return std::any{TI{}}; }},
    {"ZZToClient", []() { return std::any{ZZToClient{}}; }},
    {"ZZToServer", []() { return std::any{ZZToServer{}}; }},
    {"askchaa", []() { return std::any{askchaa{}}; }},
    {"decryptor", []() { return std::any{decryptor{}}; }},
};

}  // namespace aolib
