// AUTO-GENERATED from spec. Do not edit; run aolib-gen.
#include "aolib/registry_gen.hpp"

#include "aolib/packets_gen.hpp"
#include "aolib/wire.hpp"

namespace aolib {

const std::map<std::string, FantaDecoder> c2s_decoders = {
    {"CASEA", [](const std::vector<std::string>& b) { auto p = CASEAToServer::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<CASEAToServer>(std::move(p)))}; }},
    {"CC", [](const std::vector<std::string>& b) { auto p = CC::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<CC>(std::move(p)))}; }},
    {"CH", [](const std::vector<std::string>& b) { auto p = CH::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<CH>(std::move(p)))}; }},
    {"CT", [](const std::vector<std::string>& b) { auto p = CTToServer::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<CTToServer>(std::move(p)))}; }},
    {"DE", [](const std::vector<std::string>& b) { auto p = DE::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<DE>(std::move(p)))}; }},
    {"EE", [](const std::vector<std::string>& b) { auto p = EE::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<EE>(std::move(p)))}; }},
    {"HI", [](const std::vector<std::string>& b) { auto p = HI::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<HI>(std::move(p)))}; }},
    {"HP", [](const std::vector<std::string>& b) { auto p = HPToServer::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<HPToServer>(std::move(p)))}; }},
    {"ID", [](const std::vector<std::string>& b) { auto p = IDToServer::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<IDToServer>(std::move(p)))}; }},
    {"MA", [](const std::vector<std::string>& b) { auto p = MA::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<MA>(std::move(p)))}; }},
    {"MC", [](const std::vector<std::string>& b) { auto p = MCToServer::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<MCToServer>(std::move(p)))}; }},
    {"MS", [](const std::vector<std::string>& b) { auto p = MSToServer::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<MSToServer>(std::move(p)))}; }},
    {"PE", [](const std::vector<std::string>& b) { auto p = PE::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<PE>(std::move(p)))}; }},
    {"RC", [](const std::vector<std::string>& b) { auto p = RC::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<RC>(std::move(p)))}; }},
    {"RD", [](const std::vector<std::string>& b) { auto p = RD::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<RD>(std::move(p)))}; }},
    {"RM", [](const std::vector<std::string>& b) { auto p = RM::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<RM>(std::move(p)))}; }},
    {"RT", [](const std::vector<std::string>& b) { auto p = RTToServer::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<RTToServer>(std::move(p)))}; }},
    {"SETCASE", [](const std::vector<std::string>& b) { auto p = SETCASE::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<SETCASE>(std::move(p)))}; }},
    {"ZZ", [](const std::vector<std::string>& b) { auto p = ZZToServer::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<ZZToServer>(std::move(p)))}; }},
    {"askchaa", [](const std::vector<std::string>& b) { auto p = askchaa::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<askchaa>(std::move(p)))}; }},
};

const std::map<std::string, FantaDecoder> s2c_decoders = {
    {"ARUP", [](const std::vector<std::string>& b) { auto p = ARUP::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<ARUP>(std::move(p)))}; }},
    {"ASS", [](const std::vector<std::string>& b) { auto p = ASS::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<ASS>(std::move(p)))}; }},
    {"AUTH", [](const std::vector<std::string>& b) { auto p = AUTH::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<AUTH>(std::move(p)))}; }},
    {"BB", [](const std::vector<std::string>& b) { auto p = BB::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<BB>(std::move(p)))}; }},
    {"BD", [](const std::vector<std::string>& b) { auto p = BD::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<BD>(std::move(p)))}; }},
    {"BN", [](const std::vector<std::string>& b) { auto p = BN::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<BN>(std::move(p)))}; }},
    {"CASEA", [](const std::vector<std::string>& b) { auto p = CASEAToClient::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<CASEAToClient>(std::move(p)))}; }},
    {"CHECK", [](const std::vector<std::string>& b) { auto p = CHECK::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<CHECK>(std::move(p)))}; }},
    {"CI", [](const std::vector<std::string>& b) { auto p = CI::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<CI>(std::move(p)))}; }},
    {"CT", [](const std::vector<std::string>& b) { auto p = CTToClient::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<CTToClient>(std::move(p)))}; }},
    {"CharsCheck", [](const std::vector<std::string>& b) { auto p = CharsCheck::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<CharsCheck>(std::move(p)))}; }},
    {"DONE", [](const std::vector<std::string>& b) { auto p = DONE::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<DONE>(std::move(p)))}; }},
    {"EI", [](const std::vector<std::string>& b) { auto p = EI::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<EI>(std::move(p)))}; }},
    {"EM", [](const std::vector<std::string>& b) { auto p = EM::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<EM>(std::move(p)))}; }},
    {"FA", [](const std::vector<std::string>& b) { auto p = FA::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<FA>(std::move(p)))}; }},
    {"FL", [](const std::vector<std::string>& b) { auto p = FL::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<FL>(std::move(p)))}; }},
    {"FM", [](const std::vector<std::string>& b) { auto p = FM::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<FM>(std::move(p)))}; }},
    {"HP", [](const std::vector<std::string>& b) { auto p = HPToClient::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<HPToClient>(std::move(p)))}; }},
    {"ID", [](const std::vector<std::string>& b) { auto p = IDToClient::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<IDToClient>(std::move(p)))}; }},
    {"JD", [](const std::vector<std::string>& b) { auto p = JD::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<JD>(std::move(p)))}; }},
    {"KB", [](const std::vector<std::string>& b) { auto p = KB::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<KB>(std::move(p)))}; }},
    {"KK", [](const std::vector<std::string>& b) { auto p = KK::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<KK>(std::move(p)))}; }},
    {"LE", [](const std::vector<std::string>& b) { auto p = LE::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<LE>(std::move(p)))}; }},
    {"MC", [](const std::vector<std::string>& b) { auto p = MCToClient::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<MCToClient>(std::move(p)))}; }},
    {"MS", [](const std::vector<std::string>& b) { auto p = MSToClient::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<MSToClient>(std::move(p)))}; }},
    {"PN", [](const std::vector<std::string>& b) { auto p = PN::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<PN>(std::move(p)))}; }},
    {"PR", [](const std::vector<std::string>& b) { auto p = PR::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<PR>(std::move(p)))}; }},
    {"PU", [](const std::vector<std::string>& b) { auto p = PU::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<PU>(std::move(p)))}; }},
    {"PV", [](const std::vector<std::string>& b) { auto p = PV::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<PV>(std::move(p)))}; }},
    {"RMC", [](const std::vector<std::string>& b) { auto p = RMC::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<RMC>(std::move(p)))}; }},
    {"RT", [](const std::vector<std::string>& b) { auto p = RTToClient::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<RTToClient>(std::move(p)))}; }},
    {"SC", [](const std::vector<std::string>& b) { auto p = SC::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<SC>(std::move(p)))}; }},
    {"SI", [](const std::vector<std::string>& b) { auto p = SI::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<SI>(std::move(p)))}; }},
    {"SM", [](const std::vector<std::string>& b) { auto p = SM::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<SM>(std::move(p)))}; }},
    {"SP", [](const std::vector<std::string>& b) { auto p = SP::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<SP>(std::move(p)))}; }},
    {"ST", [](const std::vector<std::string>& b) { auto p = ST::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<ST>(std::move(p)))}; }},
    {"TI", [](const std::vector<std::string>& b) { auto p = TI::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<TI>(std::move(p)))}; }},
    {"ZZ", [](const std::vector<std::string>& b) { auto p = ZZToClient::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<ZZToClient>(std::move(p)))}; }},
    {"decryptor", [](const std::vector<std::string>& b) { auto p = decryptor::parse(b); validate_packet(p); return std::any{std::shared_ptr<Outgoing>(std::make_shared<decryptor>(std::move(p)))}; }},
};

const std::map<std::string, JsonDecoder> c2s_json = {
    {"CASEA", [](const std::string& raw) { CASEAToServer p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<CASEAToServer>(std::move(p)))}; }},
    {"CC", [](const std::string& raw) { CC p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<CC>(std::move(p)))}; }},
    {"CH", [](const std::string& raw) { CH p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<CH>(std::move(p)))}; }},
    {"CT", [](const std::string& raw) { CTToServer p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<CTToServer>(std::move(p)))}; }},
    {"DE", [](const std::string& raw) { DE p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<DE>(std::move(p)))}; }},
    {"EE", [](const std::string& raw) { EE p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<EE>(std::move(p)))}; }},
    {"HI", [](const std::string& raw) { HI p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<HI>(std::move(p)))}; }},
    {"HP", [](const std::string& raw) { HPToServer p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<HPToServer>(std::move(p)))}; }},
    {"ID", [](const std::string& raw) { IDToServer p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<IDToServer>(std::move(p)))}; }},
    {"MA", [](const std::string& raw) { MA p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<MA>(std::move(p)))}; }},
    {"MC", [](const std::string& raw) { MCToServer p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<MCToServer>(std::move(p)))}; }},
    {"MS", [](const std::string& raw) { MSToServer p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<MSToServer>(std::move(p)))}; }},
    {"PE", [](const std::string& raw) { PE p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<PE>(std::move(p)))}; }},
    {"RC", [](const std::string& raw) { RC p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<RC>(std::move(p)))}; }},
    {"RD", [](const std::string& raw) { RD p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<RD>(std::move(p)))}; }},
    {"RM", [](const std::string& raw) { RM p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<RM>(std::move(p)))}; }},
    {"RT", [](const std::string& raw) { RTToServer p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<RTToServer>(std::move(p)))}; }},
    {"SETCASE", [](const std::string& raw) { SETCASE p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<SETCASE>(std::move(p)))}; }},
    {"ZZ", [](const std::string& raw) { ZZToServer p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<ZZToServer>(std::move(p)))}; }},
    {"askchaa", [](const std::string& raw) { askchaa p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<askchaa>(std::move(p)))}; }},
};

const std::map<std::string, JsonDecoder> s2c_json = {
    {"ARUP", [](const std::string& raw) { ARUP p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<ARUP>(std::move(p)))}; }},
    {"ASS", [](const std::string& raw) { ASS p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<ASS>(std::move(p)))}; }},
    {"AUTH", [](const std::string& raw) { AUTH p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<AUTH>(std::move(p)))}; }},
    {"BB", [](const std::string& raw) { BB p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<BB>(std::move(p)))}; }},
    {"BD", [](const std::string& raw) { BD p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<BD>(std::move(p)))}; }},
    {"BN", [](const std::string& raw) { BN p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<BN>(std::move(p)))}; }},
    {"CASEA", [](const std::string& raw) { CASEAToClient p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<CASEAToClient>(std::move(p)))}; }},
    {"CHECK", [](const std::string& raw) { CHECK p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<CHECK>(std::move(p)))}; }},
    {"CI", [](const std::string& raw) { CI p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<CI>(std::move(p)))}; }},
    {"CT", [](const std::string& raw) { CTToClient p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<CTToClient>(std::move(p)))}; }},
    {"CharsCheck", [](const std::string& raw) { CharsCheck p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<CharsCheck>(std::move(p)))}; }},
    {"DONE", [](const std::string& raw) { DONE p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<DONE>(std::move(p)))}; }},
    {"EI", [](const std::string& raw) { EI p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<EI>(std::move(p)))}; }},
    {"EM", [](const std::string& raw) { EM p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<EM>(std::move(p)))}; }},
    {"FA", [](const std::string& raw) { FA p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<FA>(std::move(p)))}; }},
    {"FL", [](const std::string& raw) { FL p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<FL>(std::move(p)))}; }},
    {"FM", [](const std::string& raw) { FM p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<FM>(std::move(p)))}; }},
    {"HP", [](const std::string& raw) { HPToClient p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<HPToClient>(std::move(p)))}; }},
    {"ID", [](const std::string& raw) { IDToClient p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<IDToClient>(std::move(p)))}; }},
    {"JD", [](const std::string& raw) { JD p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<JD>(std::move(p)))}; }},
    {"KB", [](const std::string& raw) { KB p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<KB>(std::move(p)))}; }},
    {"KK", [](const std::string& raw) { KK p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<KK>(std::move(p)))}; }},
    {"LE", [](const std::string& raw) { LE p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<LE>(std::move(p)))}; }},
    {"MC", [](const std::string& raw) { MCToClient p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<MCToClient>(std::move(p)))}; }},
    {"MS", [](const std::string& raw) { MSToClient p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<MSToClient>(std::move(p)))}; }},
    {"PN", [](const std::string& raw) { PN p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<PN>(std::move(p)))}; }},
    {"PR", [](const std::string& raw) { PR p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<PR>(std::move(p)))}; }},
    {"PU", [](const std::string& raw) { PU p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<PU>(std::move(p)))}; }},
    {"PV", [](const std::string& raw) { PV p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<PV>(std::move(p)))}; }},
    {"RMC", [](const std::string& raw) { RMC p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<RMC>(std::move(p)))}; }},
    {"RT", [](const std::string& raw) { RTToClient p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<RTToClient>(std::move(p)))}; }},
    {"SC", [](const std::string& raw) { SC p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<SC>(std::move(p)))}; }},
    {"SI", [](const std::string& raw) { SI p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<SI>(std::move(p)))}; }},
    {"SM", [](const std::string& raw) { SM p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<SM>(std::move(p)))}; }},
    {"SP", [](const std::string& raw) { SP p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<SP>(std::move(p)))}; }},
    {"ST", [](const std::string& raw) { ST p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<ST>(std::move(p)))}; }},
    {"TI", [](const std::string& raw) { TI p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<TI>(std::move(p)))}; }},
    {"ZZ", [](const std::string& raw) { ZZToClient p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<ZZToClient>(std::move(p)))}; }},
    {"decryptor", [](const std::string& raw) { decryptor p; decode_json_into(p, raw); return std::any{std::shared_ptr<Outgoing>(std::make_shared<decryptor>(std::move(p)))}; }},
};

const std::map<std::string, PacketConstructor> packet_constructors = {
    {"ARUP", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<ARUP>())}; }},
    {"ASS", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<ASS>())}; }},
    {"AUTH", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<AUTH>())}; }},
    {"BB", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<BB>())}; }},
    {"BD", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<BD>())}; }},
    {"BN", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<BN>())}; }},
    {"CASEAToClient", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<CASEAToClient>())}; }},
    {"CASEAToServer", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<CASEAToServer>())}; }},
    {"CC", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<CC>())}; }},
    {"CH", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<CH>())}; }},
    {"CHECK", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<CHECK>())}; }},
    {"CI", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<CI>())}; }},
    {"CTToClient", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<CTToClient>())}; }},
    {"CTToServer", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<CTToServer>())}; }},
    {"CharsCheck", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<CharsCheck>())}; }},
    {"DE", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<DE>())}; }},
    {"DONE", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<DONE>())}; }},
    {"EE", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<EE>())}; }},
    {"EI", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<EI>())}; }},
    {"EM", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<EM>())}; }},
    {"FA", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<FA>())}; }},
    {"FL", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<FL>())}; }},
    {"FM", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<FM>())}; }},
    {"HI", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<HI>())}; }},
    {"HPToClient", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<HPToClient>())}; }},
    {"HPToServer", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<HPToServer>())}; }},
    {"IDToClient", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<IDToClient>())}; }},
    {"IDToServer", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<IDToServer>())}; }},
    {"JD", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<JD>())}; }},
    {"KB", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<KB>())}; }},
    {"KK", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<KK>())}; }},
    {"LE", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<LE>())}; }},
    {"MA", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<MA>())}; }},
    {"MCToClient", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<MCToClient>())}; }},
    {"MCToServer", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<MCToServer>())}; }},
    {"MSToClient", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<MSToClient>())}; }},
    {"MSToServer", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<MSToServer>())}; }},
    {"PE", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<PE>())}; }},
    {"PN", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<PN>())}; }},
    {"PR", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<PR>())}; }},
    {"PU", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<PU>())}; }},
    {"PV", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<PV>())}; }},
    {"RC", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<RC>())}; }},
    {"RD", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<RD>())}; }},
    {"RM", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<RM>())}; }},
    {"RMC", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<RMC>())}; }},
    {"RTToClient", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<RTToClient>())}; }},
    {"RTToServer", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<RTToServer>())}; }},
    {"SC", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<SC>())}; }},
    {"SETCASE", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<SETCASE>())}; }},
    {"SI", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<SI>())}; }},
    {"SM", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<SM>())}; }},
    {"SP", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<SP>())}; }},
    {"ST", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<ST>())}; }},
    {"TI", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<TI>())}; }},
    {"ZZToClient", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<ZZToClient>())}; }},
    {"ZZToServer", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<ZZToServer>())}; }},
    {"askchaa", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<askchaa>())}; }},
    {"decryptor", []() { return std::any{std::shared_ptr<Outgoing>(std::make_shared<decryptor>())}; }},
};

}  // namespace aolib
