// Code generated by cmd/aolib-gen from spec. DO NOT EDIT.

package aolib

// AreaUpdateType is Discriminator for ARUP payloads: 0 = player counts (numbers), 1/2/3 = area metadata strings.
type AreaUpdateType string

const (
	AreaUpdateTypePlayerCount AreaUpdateType = "player_count"
	AreaUpdateTypeStatus      AreaUpdateType = "status"
	AreaUpdateTypeCaseManager AreaUpdateType = "case_manager"
	AreaUpdateTypeLocked      AreaUpdateType = "locked"
)

var areaUpdateTypeToWire = map[AreaUpdateType]int{
	AreaUpdateTypePlayerCount: 0,
	AreaUpdateTypeStatus:      1,
	AreaUpdateTypeCaseManager: 2,
	AreaUpdateTypeLocked:      3,
}

var areaUpdateTypeFromWire = map[int]AreaUpdateType{
	0: AreaUpdateTypePlayerCount,
	1: AreaUpdateTypeStatus,
	2: AreaUpdateTypeCaseManager,
	3: AreaUpdateTypeLocked,
}

// AuthState is Moderator authentication state (AUTH packet).
type AuthState string

const (
	AuthStateLogout  AuthState = "logout"
	AuthStateFailed  AuthState = "failed"
	AuthStateSuccess AuthState = "success"
)

var authStateToWire = map[AuthState]int{
	AuthStateLogout:  -1,
	AuthStateFailed:  0,
	AuthStateSuccess: 1,
}

var authStateFromWire = map[int]AuthState{
	-1: AuthStateLogout,
	0:  AuthStateFailed,
	1:  AuthStateSuccess,
}

// CharAvailability is Per-character availability in a CharsCheck list.
type CharAvailability string

const (
	CharAvailabilityFree  CharAvailability = "free"
	CharAvailabilityTaken CharAvailability = "taken"
)

var charAvailabilityToWire = map[CharAvailability]int{
	CharAvailabilityFree:  0,
	CharAvailabilityTaken: -1,
}

var charAvailabilityFromWire = map[int]CharAvailability{
	0:  CharAvailabilityFree,
	-1: CharAvailabilityTaken,
}

// DeskModifier is Desk visibility behavior.
type DeskModifier string

const (
	DeskModifierHidden                      DeskModifier = "hidden"
	DeskModifierShown                       DeskModifier = "shown"
	DeskModifierHideDuringPreanim           DeskModifier = "hide_during_preanim"
	DeskModifierShowDuringPreanim           DeskModifier = "show_during_preanim"
	DeskModifierHideAndCenterDuringPreanim  DeskModifier = "hide_and_center_during_preanim"
	DeskModifierShowDuringPreanimThenCenter DeskModifier = "show_during_preanim_then_center"
)

var deskModifierToWire = map[DeskModifier]int{
	DeskModifierHidden:                      0,
	DeskModifierShown:                       1,
	DeskModifierHideDuringPreanim:           2,
	DeskModifierShowDuringPreanim:           3,
	DeskModifierHideAndCenterDuringPreanim:  4,
	DeskModifierShowDuringPreanimThenCenter: 5,
}

var deskModifierFromWire = map[int]DeskModifier{
	0: DeskModifierHidden,
	1: DeskModifierShown,
	2: DeskModifierHideDuringPreanim,
	3: DeskModifierShowDuringPreanim,
	4: DeskModifierHideAndCenterDuringPreanim,
	5: DeskModifierShowDuringPreanimThenCenter,
}

// EmoteModifier is Emote behavior selector. Spec values 3 and 4 are documented as unused.
type EmoteModifier string

const (
	EmoteModifierNoPreanim           EmoteModifier = "no_preanim"
	EmoteModifierPreanim             EmoteModifier = "preanim"
	EmoteModifierPreanimAndObjection EmoteModifier = "preanim_and_objection"
	EmoteModifierUnused3             EmoteModifier = "unused_3"
	EmoteModifierUnused4             EmoteModifier = "unused_4"
	EmoteModifierZoom                EmoteModifier = "zoom"
	EmoteModifierObjectionZoom       EmoteModifier = "objection_zoom"
)

var emoteModifierToWire = map[EmoteModifier]int{
	EmoteModifierNoPreanim:           0,
	EmoteModifierPreanim:             1,
	EmoteModifierPreanimAndObjection: 2,
	EmoteModifierUnused3:             3,
	EmoteModifierUnused4:             4,
	EmoteModifierZoom:                5,
	EmoteModifierObjectionZoom:       6,
}

var emoteModifierFromWire = map[int]EmoteModifier{
	0: EmoteModifierNoPreanim,
	1: EmoteModifierPreanim,
	2: EmoteModifierPreanimAndObjection,
	3: EmoteModifierUnused3,
	4: EmoteModifierUnused4,
	5: EmoteModifierZoom,
	6: EmoteModifierObjectionZoom,
}

// Flip is Sprite mirroring.
type Flip string

const (
	FlipNone                  Flip = "none"
	FlipHorizontal            Flip = "horizontal"
	FlipVertical              Flip = "vertical"
	FlipHorizontalAndVertical Flip = "horizontal_and_vertical"
)

var flipToWire = map[Flip]int{
	FlipNone:                  0,
	FlipHorizontal:            1,
	FlipVertical:              2,
	FlipHorizontalAndVertical: 3,
}

var flipFromWire = map[int]Flip{
	0: FlipNone,
	1: FlipHorizontal,
	2: FlipVertical,
	3: FlipHorizontalAndVertical,
}

// JudgeState is Judge-control visibility carried by the JD packet.
type JudgeState string

const (
	JudgeStateByPosition JudgeState = "by_position"
	JudgeStateHidden     JudgeState = "hidden"
	JudgeStateShown      JudgeState = "shown"
)

var judgeStateToWire = map[JudgeState]int{
	JudgeStateByPosition: -1,
	JudgeStateHidden:     0,
	JudgeStateShown:      1,
}

var judgeStateFromWire = map[int]JudgeState{
	-1: JudgeStateByPosition,
	0:  JudgeStateHidden,
	1:  JudgeStateShown,
}

// PenaltyBar is Which penalty (health) bar an HP packet updates.
type PenaltyBar string

const (
	PenaltyBarDefense     PenaltyBar = "defense"
	PenaltyBarProsecution PenaltyBar = "prosecution"
)

var penaltyBarToWire = map[PenaltyBar]int{
	PenaltyBarDefense:     1,
	PenaltyBarProsecution: 2,
}

var penaltyBarFromWire = map[int]PenaltyBar{
	1: PenaltyBarDefense,
	2: PenaltyBarProsecution,
}

// PlayerDataType is PU packet field selector: which playerlist datum the packet updates.
type PlayerDataType string

const (
	PlayerDataTypeOocName  PlayerDataType = "ooc_name"
	PlayerDataTypeCharName PlayerDataType = "char_name"
	PlayerDataTypeShowname PlayerDataType = "showname"
	PlayerDataTypeAreaID   PlayerDataType = "area_id"
)

var playerDataTypeToWire = map[PlayerDataType]int{
	PlayerDataTypeOocName:  0,
	PlayerDataTypeCharName: 1,
	PlayerDataTypeShowname: 2,
	PlayerDataTypeAreaID:   3,
}

var playerDataTypeFromWire = map[int]PlayerDataType{
	0: PlayerDataTypeOocName,
	1: PlayerDataTypeCharName,
	2: PlayerDataTypeShowname,
	3: PlayerDataTypeAreaID,
}

// PlayerListUpdate is PR packet update type: add or remove a player from the playerlist.
type PlayerListUpdate string

const (
	PlayerListUpdateAdd    PlayerListUpdate = "add"
	PlayerListUpdateRemove PlayerListUpdate = "remove"
)

var playerListUpdateToWire = map[PlayerListUpdate]int{
	PlayerListUpdateAdd:    0,
	PlayerListUpdateRemove: 1,
}

var playerListUpdateFromWire = map[int]PlayerListUpdate{
	0: PlayerListUpdateAdd,
	1: PlayerListUpdateRemove,
}

// RTAnimation is Judge-control overlay animation played by RT.
type RTAnimation string

const (
	RTAnimationWitnessTestimony RTAnimation = "witness_testimony"
	RTAnimationCrossExamination RTAnimation = "cross_examination"
	RTAnimationNotGuilty        RTAnimation = "not_guilty"
	RTAnimationGuilty           RTAnimation = "guilty"
	RTAnimationEndAnimation     RTAnimation = "end_animation"
	RTAnimationCustom           RTAnimation = "custom"
)

// ShoutModifier is Shout / objection selector.
type ShoutModifier string

const (
	ShoutModifierNone      ShoutModifier = "none"
	ShoutModifierHoldIt    ShoutModifier = "hold_it"
	ShoutModifierObjection ShoutModifier = "objection"
	ShoutModifierTakeThat  ShoutModifier = "take_that"
	ShoutModifierCustom    ShoutModifier = "custom"
)

var shoutModifierToWire = map[ShoutModifier]int{
	ShoutModifierNone:      0,
	ShoutModifierHoldIt:    1,
	ShoutModifierObjection: 2,
	ShoutModifierTakeThat:  3,
	ShoutModifierCustom:    4,
}

var shoutModifierFromWire = map[int]ShoutModifier{
	0: ShoutModifierNone,
	1: ShoutModifierHoldIt,
	2: ShoutModifierObjection,
	3: ShoutModifierTakeThat,
	4: ShoutModifierCustom,
}

// Side is Character position. Wire values are the lowercase 3-letter codes.
type Side string

const (
	SideDef Side = "def"
	SidePro Side = "pro"
	SideHld Side = "hld"
	SideHlp Side = "hlp"
	SideWit Side = "wit"
	SideJud Side = "jud"
	SideJur Side = "jur"
	SideSea Side = "sea"
)

// TextColor is Chat message text color. `blue` also disables the talking animation.
type TextColor string

const (
	TextColorWhite   TextColor = "white"
	TextColorGreen   TextColor = "green"
	TextColorRed     TextColor = "red"
	TextColorOrange  TextColor = "orange"
	TextColorBlue    TextColor = "blue"
	TextColorYellow  TextColor = "yellow"
	TextColorPink    TextColor = "pink"
	TextColorCyan    TextColor = "cyan"
	TextColorGrey    TextColor = "grey"
	TextColorRainbow TextColor = "rainbow"
)

var textColorToWire = map[TextColor]int{
	TextColorWhite:   0,
	TextColorGreen:   1,
	TextColorRed:     2,
	TextColorOrange:  3,
	TextColorBlue:    4,
	TextColorYellow:  5,
	TextColorPink:    6,
	TextColorCyan:    7,
	TextColorGrey:    8,
	TextColorRainbow: 9,
}

var textColorFromWire = map[int]TextColor{
	0: TextColorWhite,
	1: TextColorGreen,
	2: TextColorRed,
	3: TextColorOrange,
	4: TextColorBlue,
	5: TextColorYellow,
	6: TextColorPink,
	7: TextColorCyan,
	8: TextColorGrey,
	9: TextColorRainbow,
}

// TimerCommand is TI packet command: how to manipulate a timer.
type TimerCommand string

const (
	TimerCommandStart TimerCommand = "start"
	TimerCommandPause TimerCommand = "pause"
	TimerCommandShow  TimerCommand = "show"
	TimerCommandHide  TimerCommand = "hide"
)

var timerCommandToWire = map[TimerCommand]int{
	TimerCommandStart: 0,
	TimerCommandPause: 1,
	TimerCommandShow:  2,
	TimerCommandHide:  3,
}

var timerCommandFromWire = map[int]TimerCommand{
	0: TimerCommandStart,
	1: TimerCommandPause,
	2: TimerCommandShow,
	3: TimerCommandHide,
}
