// Code generated by cmd/aolib-gen from spec. DO NOT EDIT.

package aolib

// ARUP is
type ARUP struct {
	UpdateType AreaUpdateType `json:"update_type"`
	UpdateData []string       `json:"update_data"`
}

func (p *ARUP) Header() string { return "ARUP" }

// ASS is
type ASS struct {
	AssetUrl string `json:"asset_url"`
}

func (p *ASS) Header() string { return "ASS" }

func (p *ASS) Args() []string {
	var args []string
	args = append(args, escapeFanta(p.AssetUrl))
	return args
}

func ParseASS(body []string) (*ASS, error) {
	p := &ASS{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.AssetUrl = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// AUTH is
type AUTH struct {
	AuthState AuthState `json:"auth_state"`
}

func (p *AUTH) Header() string { return "AUTH" }

func (p *AUTH) Args() []string {
	var args []string
	args = append(args, itoa(authStateToWire[p.AuthState]))
	return args
}

func ParseAUTH(body []string) (*AUTH, error) {
	p := &AUTH{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.AuthState = authStateFromWire[atoiOrZero(get(cursor))]
	cursor++
	return p, nil
}

// Askchaa is
type Askchaa struct {
}

func (p *Askchaa) Header() string { return "askchaa" }

func (p *Askchaa) Args() []string {
	var args []string
	return args
}

func ParseAskchaa(body []string) (*Askchaa, error) {
	p := &Askchaa{}
	return p, nil
}

// BB is
type BB struct {
	Message string `json:"message"`
}

func (p *BB) Header() string { return "BB" }

func (p *BB) Args() []string {
	var args []string
	args = append(args, escapeFanta(p.Message))
	return args
}

func ParseBB(body []string) (*BB, error) {
	p := &BB{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.Message = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// BD is
type BD struct {
	Reason string `json:"reason"`
}

func (p *BD) Header() string { return "BD" }

func (p *BD) Args() []string {
	var args []string
	args = append(args, escapeFanta(p.Reason))
	return args
}

func ParseBD(body []string) (*BD, error) {
	p := &BD{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.Reason = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// BN is
type BN struct {
	Background string `json:"background"`
	Position   string `json:"position"`
}

func (p *BN) Header() string { return "BN" }

func (p *BN) Args() []string {
	var args []string
	args = append(args, escapeFanta(p.Background))
	args = append(args, escapeFanta(p.Position))
	return args
}

func ParseBN(body []string) (*BN, error) {
	p := &BN{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.Background = unescapeFanta(get(cursor))
	cursor++
	p.Position = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// CC is
type CC struct {
	PlayerID     int    `json:"player_id"`
	CharID       int    `json:"char_id"`
	CharPassword string `json:"char_password"`
}

func (p *CC) Header() string { return "CC" }

func (p *CC) Args() []string {
	var args []string
	args = append(args, itoa(p.PlayerID))
	args = append(args, itoa(p.CharID))
	args = append(args, escapeFanta(p.CharPassword))
	return args
}

func ParseCC(body []string) (*CC, error) {
	p := &CC{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.PlayerID = atoiOrZero(get(cursor))
	cursor++
	p.CharID = atoiOrZero(get(cursor))
	cursor++
	p.CharPassword = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// CH is
type CH struct {
	CharID int `json:"char_id"`
}

func (p *CH) Header() string { return "CH" }

func (p *CH) Args() []string {
	var args []string
	args = append(args, itoa(p.CharID))
	return args
}

func ParseCH(body []string) (*CH, error) {
	p := &CH{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.CharID = atoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// CHECK is
type CHECK struct {
}

func (p *CHECK) Header() string { return "CHECK" }

func (p *CHECK) Args() []string {
	var args []string
	return args
}

func ParseCHECK(body []string) (*CHECK, error) {
	p := &CHECK{}
	return p, nil
}

type CIEntriesItem struct {
	Index int    `json:"index"`
	Data  string `json:"data"`
}

func (it CIEntriesItem) wireFields() string {
	return joinAmp([]string{itoa(it.Index), escapeFanta(it.Data)})
}

func parseCIEntriesItem(s string) CIEntriesItem {
	parts := splitAmp(s, 2)
	var it CIEntriesItem
	if len(parts) > 0 {
		it.Index = atoiOrZero(parts[0])
	}
	if len(parts) > 1 {
		it.Data = unescapeFanta(parts[1])
	}
	return it
}

// CI is
type CI struct {
	BatchIndex int             `json:"batchIndex"`
	Entries    []CIEntriesItem `json:"entries"`
}

func (p *CI) Header() string { return "CI" }

func (p *CI) Args() []string {
	var args []string
	args = append(args, itoa(p.BatchIndex))
	for _, it := range p.Entries {
		args = append(args, it.wireFields())
	}
	return args
}

func ParseCI(body []string) (*CI, error) {
	p := &CI{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.BatchIndex = atoiOrZero(get(cursor))
	cursor++
	for _, slot := range body[cursor:] {
		p.Entries = append(p.Entries, parseCIEntriesItem(slot))
	}
	cursor = len(body)
	return p, nil
}

// CTToClient is
type CTToClient struct {
	Name         string `json:"name"`
	Message      string `json:"message"`
	IsFromServer bool   `json:"is_from_server"`
}

func (p *CTToClient) Header() string { return "CT" }

func (p *CTToClient) Args() []string {
	var args []string
	args = append(args, escapeFanta(p.Name))
	args = append(args, escapeFanta(p.Message))
	args = append(args, boolToWire(p.IsFromServer))
	return args
}

func ParseCTToClient(body []string) (*CTToClient, error) {
	p := &CTToClient{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.Name = unescapeFanta(get(cursor))
	cursor++
	p.Message = unescapeFanta(get(cursor))
	cursor++
	p.IsFromServer = wireToBool(get(cursor))
	cursor++
	return p, nil
}

// CTToServer is
type CTToServer struct {
	Name    string `json:"name"`
	Message string `json:"message"`
}

func (p *CTToServer) Header() string { return "CT" }

func (p *CTToServer) Args() []string {
	var args []string
	args = append(args, escapeFanta(p.Name))
	args = append(args, escapeFanta(p.Message))
	return args
}

func ParseCTToServer(body []string) (*CTToServer, error) {
	p := &CTToServer{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.Name = unescapeFanta(get(cursor))
	cursor++
	p.Message = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// CharsCheck is
type CharsCheck struct {
	Taken []CharAvailability `json:"taken"`
}

func (p *CharsCheck) Header() string { return "CharsCheck" }

func (p *CharsCheck) Args() []string {
	var args []string
	for _, v := range p.Taken {
		args = append(args, itoa(charAvailabilityToWire[v]))
	}
	return args
}

func ParseCharsCheck(body []string) (*CharsCheck, error) {
	p := &CharsCheck{}
	cursor := 0
	for _, slot := range body[cursor:] {
		p.Taken = append(p.Taken, charAvailabilityFromWire[atoiOrZero(slot)])
	}
	cursor = len(body)
	return p, nil
}

// DE is
type DE struct {
	ID int `json:"id"`
}

func (p *DE) Header() string { return "DE" }

func (p *DE) Args() []string {
	var args []string
	args = append(args, itoa(p.ID))
	return args
}

func ParseDE(body []string) (*DE, error) {
	p := &DE{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.ID = atoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// DONE is
type DONE struct {
}

func (p *DONE) Header() string { return "DONE" }

func (p *DONE) Args() []string {
	var args []string
	return args
}

func ParseDONE(body []string) (*DONE, error) {
	p := &DONE{}
	return p, nil
}

// Decryptor is
type Decryptor struct {
	Value string `json:"value"`
}

func (p *Decryptor) Header() string { return "decryptor" }

func (p *Decryptor) Args() []string {
	var args []string
	args = append(args, escapeFanta(p.Value))
	return args
}

func ParseDecryptor(body []string) (*Decryptor, error) {
	p := &Decryptor{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.Value = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// EE is
type EE struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Image       string `json:"image"`
}

func (p *EE) Header() string { return "EE" }

func (p *EE) Args() []string {
	var args []string
	args = append(args, itoa(p.ID))
	args = append(args, escapeFanta(p.Name))
	args = append(args, escapeFanta(p.Description))
	args = append(args, escapeFanta(p.Image))
	return args
}

func ParseEE(body []string) (*EE, error) {
	p := &EE{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.ID = atoiOrZero(get(cursor))
	cursor++
	p.Name = unescapeFanta(get(cursor))
	cursor++
	p.Description = unescapeFanta(get(cursor))
	cursor++
	p.Image = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

type EIDetails struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Type        string `json:"type"`
	Image       string `json:"image"`
}

func (it EIDetails) wireFields() string {
	return joinAmp([]string{escapeFanta(it.Name), escapeFanta(it.Description), escapeFanta(it.Type), escapeFanta(it.Image)})
}

func parseEIDetails(s string) EIDetails {
	parts := splitAmp(s, 4)
	var it EIDetails
	if len(parts) > 0 {
		it.Name = unescapeFanta(parts[0])
	}
	if len(parts) > 1 {
		it.Description = unescapeFanta(parts[1])
	}
	if len(parts) > 2 {
		it.Type = unescapeFanta(parts[2])
	}
	if len(parts) > 3 {
		it.Image = unescapeFanta(parts[3])
	}
	return it
}

// EI is
type EI struct {
	ID      int       `json:"id"`
	Details EIDetails `json:"details"`
}

func (p *EI) Header() string { return "EI" }

func (p *EI) Args() []string {
	var args []string
	args = append(args, itoa(p.ID))
	args = append(args, p.Details.wireFields())
	return args
}

func ParseEI(body []string) (*EI, error) {
	p := &EI{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.ID = atoiOrZero(get(cursor))
	cursor++
	p.Details = parseEIDetails(get(cursor))
	cursor++
	return p, nil
}

type EMEntriesItem struct {
	Index int    `json:"index"`
	Name  string `json:"name"`
}

func (it EMEntriesItem) wireFields() string {
	return joinAmp([]string{itoa(it.Index), escapeFanta(it.Name)})
}

func parseEMEntriesItem(s string) EMEntriesItem {
	parts := splitAmp(s, 2)
	var it EMEntriesItem
	if len(parts) > 0 {
		it.Index = atoiOrZero(parts[0])
	}
	if len(parts) > 1 {
		it.Name = unescapeFanta(parts[1])
	}
	return it
}

// EM is
type EM struct {
	BatchIndex int             `json:"batchIndex"`
	Entries    []EMEntriesItem `json:"entries"`
}

func (p *EM) Header() string { return "EM" }

func (p *EM) Args() []string {
	var args []string
	args = append(args, itoa(p.BatchIndex))
	for _, it := range p.Entries {
		args = append(args, it.wireFields())
	}
	return args
}

func ParseEM(body []string) (*EM, error) {
	p := &EM{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.BatchIndex = atoiOrZero(get(cursor))
	cursor++
	for _, slot := range body[cursor:] {
		p.Entries = append(p.Entries, parseEMEntriesItem(slot))
	}
	cursor = len(body)
	return p, nil
}

// FA is
type FA struct {
	Areas []string `json:"areas"`
}

func (p *FA) Header() string { return "FA" }

func (p *FA) Args() []string {
	var args []string
	for _, v := range p.Areas {
		args = append(args, escapeFanta(v))
	}
	return args
}

func ParseFA(body []string) (*FA, error) {
	p := &FA{}
	cursor := 0
	p.Areas = []string{}
	for _, slot := range body[cursor:] {
		p.Areas = append(p.Areas, unescapeFanta(slot))
	}
	cursor = len(body)
	return p, nil
}

// FL is
type FL struct {
	Features []string `json:"features"`
}

func (p *FL) Header() string { return "FL" }

func (p *FL) Args() []string {
	var args []string
	for _, v := range p.Features {
		args = append(args, escapeFanta(v))
	}
	return args
}

func ParseFL(body []string) (*FL, error) {
	p := &FL{}
	cursor := 0
	p.Features = []string{}
	for _, slot := range body[cursor:] {
		p.Features = append(p.Features, unescapeFanta(slot))
	}
	cursor = len(body)
	return p, nil
}

type FMMusicListItem struct {
	Name string `json:"name"`
}

func (it FMMusicListItem) wireFields() string {
	return joinAmp([]string{escapeFanta(it.Name)})
}

func parseFMMusicListItem(s string) FMMusicListItem {
	parts := splitAmp(s, 1)
	var it FMMusicListItem
	if len(parts) > 0 {
		it.Name = unescapeFanta(parts[0])
	}
	return it
}

// FM is
type FM struct {
	MusicList []FMMusicListItem `json:"music_list"`
}

func (p *FM) Header() string { return "FM" }

func (p *FM) Args() []string {
	var args []string
	for _, it := range p.MusicList {
		args = append(args, it.wireFields())
	}
	return args
}

func ParseFM(body []string) (*FM, error) {
	p := &FM{}
	cursor := 0
	for _, slot := range body[cursor:] {
		p.MusicList = append(p.MusicList, parseFMMusicListItem(slot))
	}
	cursor = len(body)
	return p, nil
}

// HI is
type HI struct {
	HDID string `json:"hdid"`
}

func (p *HI) Header() string { return "HI" }

func (p *HI) Args() []string {
	var args []string
	args = append(args, escapeFanta(p.HDID))
	return args
}

func ParseHI(body []string) (*HI, error) {
	p := &HI{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.HDID = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// HPToClient is
type HPToClient struct {
	Bar   PenaltyBar `json:"bar"`
	Value int        `json:"value"`
}

func (p *HPToClient) Header() string { return "HP" }

func (p *HPToClient) Args() []string {
	var args []string
	args = append(args, itoa(penaltyBarToWire[p.Bar]))
	args = append(args, itoa(p.Value))
	return args
}

func ParseHPToClient(body []string) (*HPToClient, error) {
	p := &HPToClient{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.Bar = penaltyBarFromWire[atoiOrZero(get(cursor))]
	cursor++
	p.Value = atoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// HPToServer is
type HPToServer struct {
	Bar   PenaltyBar `json:"bar"`
	Value int        `json:"value"`
}

func (p *HPToServer) Header() string { return "HP" }

func (p *HPToServer) Args() []string {
	var args []string
	args = append(args, itoa(penaltyBarToWire[p.Bar]))
	args = append(args, itoa(p.Value))
	return args
}

func ParseHPToServer(body []string) (*HPToServer, error) {
	p := &HPToServer{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.Bar = penaltyBarFromWire[atoiOrZero(get(cursor))]
	cursor++
	p.Value = atoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// IDToClient is
type IDToClient struct {
	PlayerID int    `json:"player_id"`
	Software string `json:"software"`
	Version  string `json:"version"`
}

func (p *IDToClient) Header() string { return "ID" }

func (p *IDToClient) Args() []string {
	var args []string
	args = append(args, itoa(p.PlayerID))
	args = append(args, escapeFanta(p.Software))
	args = append(args, escapeFanta(p.Version))
	return args
}

func ParseIDToClient(body []string) (*IDToClient, error) {
	p := &IDToClient{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.PlayerID = atoiOrZero(get(cursor))
	cursor++
	p.Software = unescapeFanta(get(cursor))
	cursor++
	p.Version = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// IDToServer is
type IDToServer struct {
	Software string `json:"software"`
	Version  string `json:"version"`
}

func (p *IDToServer) Header() string { return "ID" }

func (p *IDToServer) Args() []string {
	var args []string
	args = append(args, escapeFanta(p.Software))
	args = append(args, escapeFanta(p.Version))
	return args
}

func ParseIDToServer(body []string) (*IDToServer, error) {
	p := &IDToServer{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.Software = unescapeFanta(get(cursor))
	cursor++
	p.Version = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// JD is
type JD struct {
	State JudgeState `json:"state"`
}

func (p *JD) Header() string { return "JD" }

func (p *JD) Args() []string {
	var args []string
	args = append(args, itoa(judgeStateToWire[p.State]))
	return args
}

func ParseJD(body []string) (*JD, error) {
	p := &JD{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.State = judgeStateFromWire[atoiOrZero(get(cursor))]
	cursor++
	return p, nil
}

// KB is
type KB struct {
	Reason string `json:"reason"`
}

func (p *KB) Header() string { return "KB" }

func (p *KB) Args() []string {
	var args []string
	args = append(args, escapeFanta(p.Reason))
	return args
}

func ParseKB(body []string) (*KB, error) {
	p := &KB{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.Reason = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// KK is
type KK struct {
	Reason string `json:"reason"`
}

func (p *KK) Header() string { return "KK" }

func (p *KK) Args() []string {
	var args []string
	args = append(args, escapeFanta(p.Reason))
	return args
}

func ParseKK(body []string) (*KK, error) {
	p := &KK{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.Reason = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

type LEEvidenceItem struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Image       string `json:"image"`
}

func (it LEEvidenceItem) wireFields() string {
	return joinAmp([]string{escapeFanta(it.Name), escapeFanta(it.Description), escapeFanta(it.Image)})
}

func parseLEEvidenceItem(s string) LEEvidenceItem {
	parts := splitAmp(s, 3)
	var it LEEvidenceItem
	if len(parts) > 0 {
		it.Name = unescapeFanta(parts[0])
	}
	if len(parts) > 1 {
		it.Description = unescapeFanta(parts[1])
	}
	if len(parts) > 2 {
		it.Image = unescapeFanta(parts[2])
	}
	return it
}

// LE is
type LE struct {
	Evidence []LEEvidenceItem `json:"evidence"`
}

func (p *LE) Header() string { return "LE" }

func (p *LE) Args() []string {
	var args []string
	for _, it := range p.Evidence {
		args = append(args, it.wireFields())
	}
	return args
}

func ParseLE(body []string) (*LE, error) {
	p := &LE{}
	cursor := 0
	for _, slot := range body[cursor:] {
		p.Evidence = append(p.Evidence, parseLEEvidenceItem(slot))
	}
	cursor = len(body)
	return p, nil
}

// MA is
type MA struct {
	PlayerID        int    `json:"player_id"`
	DurationMinutes int    `json:"duration_minutes"`
	Reason          string `json:"reason"`
}

func (p *MA) Header() string { return "MA" }

func (p *MA) Args() []string {
	var args []string
	args = append(args, itoa(p.PlayerID))
	args = append(args, itoa(p.DurationMinutes))
	args = append(args, escapeFanta(p.Reason))
	return args
}

func ParseMA(body []string) (*MA, error) {
	p := &MA{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.PlayerID = atoiOrZero(get(cursor))
	cursor++
	p.DurationMinutes = atoiOrZero(get(cursor))
	cursor++
	p.Reason = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// MCToClient is
type MCToClient struct {
	Name     string       `json:"name"`
	CharID   int          `json:"char_id"`
	Showname string       `json:"showname"`
	Looping  bool         `json:"looping"`
	Channel  MusicChannel `json:"channel"`
	Effects  MusicEffects `json:"effects"`
}

func (p *MCToClient) Header() string { return "MC" }

func (p *MCToClient) Args() []string {
	var args []string
	args = append(args, escapeFanta(p.Name))
	args = append(args, itoa(p.CharID))
	args = append(args, escapeFanta(p.Showname))
	args = append(args, boolToWire(p.Looping))
	args = append(args, itoa(musicChannelToWire[p.Channel]))
	args = append(args, musicEffectsToWire(p.Effects))
	return args
}

func ParseMCToClient(body []string) (*MCToClient, error) {
	p := &MCToClient{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.Name = unescapeFanta(get(cursor))
	cursor++
	p.CharID = atoiOrZero(get(cursor))
	cursor++
	p.Showname = unescapeFanta(get(cursor))
	cursor++
	p.Looping = wireToBool(get(cursor))
	cursor++
	p.Channel = musicChannelFromWire[atoiOrZero(get(cursor))]
	cursor++
	p.Effects = musicEffectsFromWire(get(cursor))
	cursor++
	return p, nil
}

// MCToServer is
type MCToServer struct {
	Name     string       `json:"name"`
	CharID   int          `json:"char_id"`
	Showname string       `json:"showname"`
	Effects  MusicEffects `json:"effects"`
}

func (p *MCToServer) Header() string { return "MC" }

func (p *MCToServer) Args() []string {
	var args []string
	args = append(args, escapeFanta(p.Name))
	args = append(args, itoa(p.CharID))
	args = append(args, escapeFanta(p.Showname))
	args = append(args, musicEffectsToWire(p.Effects))
	return args
}

func ParseMCToServer(body []string) (*MCToServer, error) {
	p := &MCToServer{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.Name = unescapeFanta(get(cursor))
	cursor++
	p.CharID = atoiOrZero(get(cursor))
	cursor++
	p.Showname = unescapeFanta(get(cursor))
	cursor++
	p.Effects = musicEffectsFromWire(get(cursor))
	cursor++
	return p, nil
}

// MSToClient is
type MSToClient struct {
	DeskModifier           DeskModifier  `json:"desk_modifier"`
	Preanim                string        `json:"preanim"`
	Character              string        `json:"character"`
	Emote                  string        `json:"emote"`
	Message                string        `json:"message"`
	Side                   Side          `json:"side"`
	SfxName                string        `json:"sfx_name"`
	EmoteModifier          EmoteModifier `json:"emote_modifier"`
	CharID                 int           `json:"char_id"`
	SfxDelay               int           `json:"sfx_delay"`
	ShoutModifier          ShoutModifier `json:"shout_modifier"`
	EvidenceID             int           `json:"evidence_id"`
	Flip                   Flip          `json:"flip"`
	Realization            bool          `json:"realization"`
	TextColor              TextColor     `json:"text_color"`
	Showname               string        `json:"showname"`
	PairedCharID           int           `json:"paired_charid"`
	PairedName             string        `json:"paired_name"`
	PairedEmote            string        `json:"paired_emote"`
	Offset                 Offset        `json:"offset"`
	PairedOffset           Offset        `json:"paired_offset"`
	PairedFlip             Flip          `json:"paired_flip"`
	NoninterruptingPreanim bool          `json:"noninterrupting_preanim"`
	SfxLooping             bool          `json:"sfx_looping"`
	Screenshake            bool          `json:"screenshake"`
	FramesShake            string        `json:"frames_shake"`
	FramesRealization      string        `json:"frames_realization"`
	FramesSfx              string        `json:"frames_sfx"`
	Additive               bool          `json:"additive"`
	Effect                 Effect        `json:"effect"`
}

func (p *MSToClient) Header() string { return "MS" }

func (p *MSToClient) Args() []string {
	var args []string
	args = append(args, itoa(deskModifierToWire[p.DeskModifier]))
	args = append(args, escapeFanta(p.Preanim))
	args = append(args, escapeFanta(p.Character))
	args = append(args, escapeFanta(p.Emote))
	args = append(args, escapeFanta(p.Message))
	args = append(args, string(p.Side))
	args = append(args, escapeFanta(p.SfxName))
	args = append(args, itoa(emoteModifierToWire[p.EmoteModifier]))
	args = append(args, itoa(p.CharID))
	args = append(args, itoa(p.SfxDelay))
	args = append(args, itoa(shoutModifierToWire[p.ShoutModifier]))
	args = append(args, itoa(p.EvidenceID))
	args = append(args, itoa(flipToWire[p.Flip]))
	args = append(args, boolToWire(p.Realization))
	args = append(args, itoa(textColorToWire[p.TextColor]))
	args = append(args, escapeFanta(p.Showname))
	args = append(args, itoa(p.PairedCharID))
	args = append(args, escapeFanta(p.PairedName))
	args = append(args, escapeFanta(p.PairedEmote))
	args = append(args, offsetToWire(p.Offset))
	args = append(args, offsetToWire(p.PairedOffset))
	args = append(args, itoa(flipToWire[p.PairedFlip]))
	args = append(args, boolToWire(p.NoninterruptingPreanim))
	args = append(args, boolToWire(p.SfxLooping))
	args = append(args, boolToWire(p.Screenshake))
	args = append(args, escapeFanta(p.FramesShake))
	args = append(args, escapeFanta(p.FramesRealization))
	args = append(args, escapeFanta(p.FramesSfx))
	args = append(args, boolToWire(p.Additive))
	args = append(args, effectToWire(p.Effect))
	return args
}

func ParseMSToClient(body []string) (*MSToClient, error) {
	p := &MSToClient{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	if cursor < len(body) {
		p.DeskModifier = deskModifierFromWire[atoiOrZero(get(cursor))]
	} else {
		p.DeskModifier = DeskModifier("shown")
	}
	cursor++
	p.Preanim = unescapeFanta(get(cursor))
	cursor++
	p.Character = unescapeFanta(get(cursor))
	cursor++
	p.Emote = unescapeFanta(get(cursor))
	cursor++
	p.Message = unescapeFanta(get(cursor))
	cursor++
	p.Side = Side(get(cursor))
	cursor++
	p.SfxName = unescapeFanta(get(cursor))
	cursor++
	p.EmoteModifier = emoteModifierFromWire[atoiOrZero(get(cursor))]
	cursor++
	p.CharID = atoiOrZero(get(cursor))
	cursor++
	p.SfxDelay = atoiOrZero(get(cursor))
	cursor++
	p.ShoutModifier = shoutModifierFromWire[atoiOrZero(get(cursor))]
	cursor++
	p.EvidenceID = atoiOrZero(get(cursor))
	cursor++
	p.Flip = flipFromWire[atoiOrZero(get(cursor))]
	cursor++
	p.Realization = wireToBool(get(cursor))
	cursor++
	p.TextColor = textColorFromWire[atoiOrZero(get(cursor))]
	cursor++
	p.Showname = unescapeFanta(get(cursor))
	cursor++
	if cursor < len(body) {
		p.PairedCharID = atoiOrZero(get(cursor))
	} else {
		p.PairedCharID = -1
	}
	cursor++
	p.PairedName = unescapeFanta(get(cursor))
	cursor++
	p.PairedEmote = unescapeFanta(get(cursor))
	cursor++
	p.Offset = offsetFromWire(get(cursor))
	cursor++
	p.PairedOffset = offsetFromWire(get(cursor))
	cursor++
	p.PairedFlip = flipFromWire[atoiOrZero(get(cursor))]
	cursor++
	p.NoninterruptingPreanim = wireToBool(get(cursor))
	cursor++
	p.SfxLooping = wireToBool(get(cursor))
	cursor++
	p.Screenshake = wireToBool(get(cursor))
	cursor++
	p.FramesShake = unescapeFanta(get(cursor))
	cursor++
	p.FramesRealization = unescapeFanta(get(cursor))
	cursor++
	p.FramesSfx = unescapeFanta(get(cursor))
	cursor++
	p.Additive = wireToBool(get(cursor))
	cursor++
	p.Effect = effectFromWire(get(cursor))
	cursor++
	return p, nil
}

// MSToServer is
type MSToServer struct {
	DeskModifier           DeskModifier  `json:"desk_modifier"`
	Preanim                string        `json:"preanim"`
	Character              string        `json:"character"`
	Emote                  string        `json:"emote"`
	Message                string        `json:"message"`
	Side                   Side          `json:"side"`
	SfxName                string        `json:"sfx_name"`
	EmoteModifier          EmoteModifier `json:"emote_modifier"`
	CharID                 int           `json:"char_id"`
	SfxDelay               int           `json:"sfx_delay"`
	ShoutModifier          ShoutModifier `json:"shout_modifier"`
	EvidenceID             int           `json:"evidence_id"`
	Flip                   Flip          `json:"flip"`
	Realization            bool          `json:"realization"`
	TextColor              TextColor     `json:"text_color"`
	Showname               string        `json:"showname"`
	PairedCharID           int           `json:"paired_charid"`
	Offset                 Offset        `json:"offset"`
	NoninterruptingPreanim bool          `json:"noninterrupting_preanim"`
	SfxLooping             bool          `json:"sfx_looping"`
	Screenshake            bool          `json:"screenshake"`
	FramesShake            string        `json:"frames_shake"`
	FramesRealization      string        `json:"frames_realization"`
	FramesSfx              string        `json:"frames_sfx"`
	Additive               bool          `json:"additive"`
	Effect                 Effect        `json:"effect"`
}

func (p *MSToServer) Header() string { return "MS" }

func (p *MSToServer) Args() []string {
	var args []string
	args = append(args, itoa(deskModifierToWire[p.DeskModifier]))
	args = append(args, escapeFanta(p.Preanim))
	args = append(args, escapeFanta(p.Character))
	args = append(args, escapeFanta(p.Emote))
	args = append(args, escapeFanta(p.Message))
	args = append(args, string(p.Side))
	args = append(args, escapeFanta(p.SfxName))
	args = append(args, itoa(emoteModifierToWire[p.EmoteModifier]))
	args = append(args, itoa(p.CharID))
	args = append(args, itoa(p.SfxDelay))
	args = append(args, itoa(shoutModifierToWire[p.ShoutModifier]))
	args = append(args, itoa(p.EvidenceID))
	args = append(args, itoa(flipToWire[p.Flip]))
	args = append(args, boolToWire(p.Realization))
	args = append(args, itoa(textColorToWire[p.TextColor]))
	args = append(args, escapeFanta(p.Showname))
	args = append(args, itoa(p.PairedCharID))
	args = append(args, offsetToWire(p.Offset))
	args = append(args, boolToWire(p.NoninterruptingPreanim))
	args = append(args, boolToWire(p.SfxLooping))
	args = append(args, boolToWire(p.Screenshake))
	args = append(args, escapeFanta(p.FramesShake))
	args = append(args, escapeFanta(p.FramesRealization))
	args = append(args, escapeFanta(p.FramesSfx))
	args = append(args, boolToWire(p.Additive))
	args = append(args, effectToWire(p.Effect))
	return args
}

func ParseMSToServer(body []string) (*MSToServer, error) {
	p := &MSToServer{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	if cursor < len(body) {
		p.DeskModifier = deskModifierFromWire[atoiOrZero(get(cursor))]
	} else {
		p.DeskModifier = DeskModifier("shown")
	}
	cursor++
	p.Preanim = unescapeFanta(get(cursor))
	cursor++
	p.Character = unescapeFanta(get(cursor))
	cursor++
	p.Emote = unescapeFanta(get(cursor))
	cursor++
	p.Message = unescapeFanta(get(cursor))
	cursor++
	p.Side = Side(get(cursor))
	cursor++
	p.SfxName = unescapeFanta(get(cursor))
	cursor++
	p.EmoteModifier = emoteModifierFromWire[atoiOrZero(get(cursor))]
	cursor++
	p.CharID = atoiOrZero(get(cursor))
	cursor++
	p.SfxDelay = atoiOrZero(get(cursor))
	cursor++
	p.ShoutModifier = shoutModifierFromWire[atoiOrZero(get(cursor))]
	cursor++
	p.EvidenceID = atoiOrZero(get(cursor))
	cursor++
	p.Flip = flipFromWire[atoiOrZero(get(cursor))]
	cursor++
	p.Realization = wireToBool(get(cursor))
	cursor++
	p.TextColor = textColorFromWire[atoiOrZero(get(cursor))]
	cursor++
	p.Showname = unescapeFanta(get(cursor))
	cursor++
	if cursor < len(body) {
		p.PairedCharID = atoiOrZero(get(cursor))
	} else {
		p.PairedCharID = -1
	}
	cursor++
	p.Offset = offsetFromWire(get(cursor))
	cursor++
	p.NoninterruptingPreanim = wireToBool(get(cursor))
	cursor++
	p.SfxLooping = wireToBool(get(cursor))
	cursor++
	p.Screenshake = wireToBool(get(cursor))
	cursor++
	p.FramesShake = unescapeFanta(get(cursor))
	cursor++
	p.FramesRealization = unescapeFanta(get(cursor))
	cursor++
	p.FramesSfx = unescapeFanta(get(cursor))
	cursor++
	p.Additive = wireToBool(get(cursor))
	cursor++
	p.Effect = effectFromWire(get(cursor))
	cursor++
	return p, nil
}

// PE is
type PE struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Image       string `json:"image"`
}

func (p *PE) Header() string { return "PE" }

func (p *PE) Args() []string {
	var args []string
	args = append(args, escapeFanta(p.Name))
	args = append(args, escapeFanta(p.Description))
	args = append(args, escapeFanta(p.Image))
	return args
}

func ParsePE(body []string) (*PE, error) {
	p := &PE{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.Name = unescapeFanta(get(cursor))
	cursor++
	p.Description = unescapeFanta(get(cursor))
	cursor++
	p.Image = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// PN is
type PN struct {
	PlayerCount       int    `json:"player_count"`
	MaxPlayers        int    `json:"max_players"`
	ServerDescription string `json:"server_description"`
}

func (p *PN) Header() string { return "PN" }

func (p *PN) Args() []string {
	var args []string
	args = append(args, itoa(p.PlayerCount))
	args = append(args, itoa(p.MaxPlayers))
	args = append(args, escapeFanta(p.ServerDescription))
	return args
}

func ParsePN(body []string) (*PN, error) {
	p := &PN{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.PlayerCount = atoiOrZero(get(cursor))
	cursor++
	p.MaxPlayers = atoiOrZero(get(cursor))
	cursor++
	p.ServerDescription = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// PR is
type PR struct {
	ID   int              `json:"id"`
	Type PlayerListUpdate `json:"type"`
}

func (p *PR) Header() string { return "PR" }

func (p *PR) Args() []string {
	var args []string
	args = append(args, itoa(p.ID))
	args = append(args, itoa(playerListUpdateToWire[p.Type]))
	return args
}

func ParsePR(body []string) (*PR, error) {
	p := &PR{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.ID = atoiOrZero(get(cursor))
	cursor++
	p.Type = playerListUpdateFromWire[atoiOrZero(get(cursor))]
	cursor++
	return p, nil
}

// PU is
type PU struct {
	ID   int            `json:"id"`
	Type PlayerDataType `json:"type"`
	Data string         `json:"data"`
}

func (p *PU) Header() string { return "PU" }

func (p *PU) Args() []string {
	var args []string
	args = append(args, itoa(p.ID))
	args = append(args, itoa(playerDataTypeToWire[p.Type]))
	args = append(args, escapeFanta(p.Data))
	return args
}

func ParsePU(body []string) (*PU, error) {
	p := &PU{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.ID = atoiOrZero(get(cursor))
	cursor++
	p.Type = playerDataTypeFromWire[atoiOrZero(get(cursor))]
	cursor++
	p.Data = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// PV is
type PV struct {
	PlayerID int `json:"player_id"`
	CharID   int `json:"char_id"`
}

func (p *PV) Header() string { return "PV" }

func (p *PV) jsonConsts() map[string]string {
	return map[string]string{"_cid": "CID"}
}

func (p *PV) Args() []string {
	var args []string
	args = append(args, itoa(p.PlayerID))
	args = append(args, "CID")
	args = append(args, itoa(p.CharID))
	return args
}

func ParsePV(body []string) (*PV, error) {
	p := &PV{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.PlayerID = atoiOrZero(get(cursor))
	cursor++
	cursor++ // const slot
	p.CharID = atoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// RC is
type RC struct {
}

func (p *RC) Header() string { return "RC" }

func (p *RC) Args() []string {
	var args []string
	return args
}

func ParseRC(body []string) (*RC, error) {
	p := &RC{}
	return p, nil
}

// RD is
type RD struct {
}

func (p *RD) Header() string { return "RD" }

func (p *RD) Args() []string {
	var args []string
	return args
}

func ParseRD(body []string) (*RD, error) {
	p := &RD{}
	return p, nil
}

// RM is
type RM struct {
}

func (p *RM) Header() string { return "RM" }

func (p *RM) Args() []string {
	var args []string
	return args
}

func ParseRM(body []string) (*RM, error) {
	p := &RM{}
	return p, nil
}

// RMC is
type RMC struct {
	ToTime string `json:"toTime"`
}

func (p *RMC) Header() string { return "RMC" }

func (p *RMC) Args() []string {
	var args []string
	args = append(args, escapeFanta(p.ToTime))
	return args
}

func ParseRMC(body []string) (*RMC, error) {
	p := &RMC{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.ToTime = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// RTToClient is
type RTToClient struct {
	Animation RTAnimation `json:"animation"`
	Name      string      `json:"name"`
}

func (p *RTToClient) Header() string { return "RT" }

// RTToServer is
type RTToServer struct {
	Animation RTAnimation `json:"animation"`
	Name      string      `json:"name"`
}

func (p *RTToServer) Header() string { return "RT" }

type SCCharDataItem struct {
	Name     string `json:"name"`
	Desc     string `json:"desc"`
	Evidence string `json:"evidence"`
}

func (it SCCharDataItem) wireFields() string {
	return joinAmp([]string{escapeFanta(it.Name), escapeFanta(it.Desc), escapeFanta(it.Evidence)})
}

func parseSCCharDataItem(s string) SCCharDataItem {
	parts := splitAmp(s, 3)
	var it SCCharDataItem
	if len(parts) > 0 {
		it.Name = unescapeFanta(parts[0])
	}
	if len(parts) > 1 {
		it.Desc = unescapeFanta(parts[1])
	}
	if len(parts) > 2 {
		it.Evidence = unescapeFanta(parts[2])
	}
	return it
}

// SC is
type SC struct {
	CharData []SCCharDataItem `json:"char_data"`
}

func (p *SC) Header() string { return "SC" }

func (p *SC) Args() []string {
	var args []string
	for _, it := range p.CharData {
		args = append(args, it.wireFields())
	}
	return args
}

func ParseSC(body []string) (*SC, error) {
	p := &SC{}
	cursor := 0
	for _, slot := range body[cursor:] {
		p.CharData = append(p.CharData, parseSCCharDataItem(slot))
	}
	cursor = len(body)
	return p, nil
}

// SI is
type SI struct {
	CharCount int `json:"char_count"`
	EviCount  int `json:"evi_count"`
	MusCount  int `json:"mus_count"`
}

func (p *SI) Header() string { return "SI" }

func (p *SI) Args() []string {
	var args []string
	args = append(args, itoa(p.CharCount))
	args = append(args, itoa(p.EviCount))
	args = append(args, itoa(p.MusCount))
	return args
}

func ParseSI(body []string) (*SI, error) {
	p := &SI{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.CharCount = atoiOrZero(get(cursor))
	cursor++
	p.EviCount = atoiOrZero(get(cursor))
	cursor++
	p.MusCount = atoiOrZero(get(cursor))
	cursor++
	return p, nil
}

type SMMusicListItem struct {
	Name string `json:"name"`
}

func (it SMMusicListItem) wireFields() string {
	return joinAmp([]string{escapeFanta(it.Name)})
}

func parseSMMusicListItem(s string) SMMusicListItem {
	parts := splitAmp(s, 1)
	var it SMMusicListItem
	if len(parts) > 0 {
		it.Name = unescapeFanta(parts[0])
	}
	return it
}

// SM is
type SM struct {
	MusicList []SMMusicListItem `json:"music_list"`
}

func (p *SM) Header() string { return "SM" }

func (p *SM) Args() []string {
	var args []string
	for _, it := range p.MusicList {
		args = append(args, it.wireFields())
	}
	return args
}

func ParseSM(body []string) (*SM, error) {
	p := &SM{}
	cursor := 0
	for _, slot := range body[cursor:] {
		p.MusicList = append(p.MusicList, parseSMMusicListItem(slot))
	}
	cursor = len(body)
	return p, nil
}

// SP is
type SP struct {
	Side Side `json:"side"`
}

func (p *SP) Header() string { return "SP" }

func (p *SP) Args() []string {
	var args []string
	args = append(args, string(p.Side))
	return args
}

func ParseSP(body []string) (*SP, error) {
	p := &SP{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.Side = Side(get(cursor))
	cursor++
	return p, nil
}

// TI is
type TI struct {
	TimerID int          `json:"timer_id"`
	Command TimerCommand `json:"command"`
	Time    int          `json:"time"`
}

func (p *TI) Header() string { return "TI" }

func (p *TI) Args() []string {
	var args []string
	args = append(args, itoa(p.TimerID))
	args = append(args, itoa(timerCommandToWire[p.Command]))
	args = append(args, itoa(p.Time))
	return args
}

func ParseTI(body []string) (*TI, error) {
	p := &TI{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.TimerID = atoiOrZero(get(cursor))
	cursor++
	p.Command = timerCommandFromWire[atoiOrZero(get(cursor))]
	cursor++
	p.Time = atoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// ZZToClient is
type ZZToClient struct {
	Reason string `json:"reason"`
}

func (p *ZZToClient) Header() string { return "ZZ" }

func (p *ZZToClient) Args() []string {
	var args []string
	args = append(args, escapeFanta(p.Reason))
	return args
}

func ParseZZToClient(body []string) (*ZZToClient, error) {
	p := &ZZToClient{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.Reason = unescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// ZZToServer is
type ZZToServer struct {
	Reason           string `json:"reason"`
	ReportedPlayerID int    `json:"reported_player_id"`
}

func (p *ZZToServer) Header() string { return "ZZ" }

func (p *ZZToServer) Args() []string {
	var args []string
	args = append(args, escapeFanta(p.Reason))
	args = append(args, itoa(p.ReportedPlayerID))
	return args
}

func ParseZZToServer(body []string) (*ZZToServer, error) {
	p := &ZZToServer{}
	get := func(i int) string {
		if i < len(body) {
			return body[i]
		}
		return ""
	}
	cursor := 0
	p.Reason = unescapeFanta(get(cursor))
	cursor++
	if cursor < len(body) {
		p.ReportedPlayerID = atoiOrZero(get(cursor))
	} else {
		p.ReportedPlayerID = -1
	}
	cursor++
	return p, nil
}
