package aolib

// Code generated by cmd/aolib-gen. DO NOT EDIT.

// Typed On*/Send* methods keyed by wire header as a TYPE, so wrong-direction
// calls don't compile and IDEs autocomplete the header.

// ClientSession is the server-side view (remote client): send S2C, on C2S.
func (c *ClientSession) SendARUP(p *ARUP)             { c.s.send(p) }
func (c *ClientSession) SendASS(p *ASS)               { c.s.send(p) }
func (c *ClientSession) SendAUTH(p *AUTH)             { c.s.send(p) }
func (c *ClientSession) SendBB(p *BB)                 { c.s.send(p) }
func (c *ClientSession) SendBD(p *BD)                 { c.s.send(p) }
func (c *ClientSession) SendBN(p *BN)                 { c.s.send(p) }
func (c *ClientSession) OnCC(h func(*CC))             { c.s.on("CC", func(p any) { h(p.(*CC)) }) }
func (c *ClientSession) SendCHECK(p *CHECK)           { c.s.send(p) }
func (c *ClientSession) SendCT(p *CTToClient)         { c.s.send(p) }
func (c *ClientSession) OnCT(h func(*CTToServer))     { c.s.on("CT", func(p any) { h(p.(*CTToServer)) }) }
func (c *ClientSession) SendCharsCheck(p *CharsCheck) { c.s.send(p) }
func (c *ClientSession) OnDE(h func(*DE))             { c.s.on("DE", func(p any) { h(p.(*DE)) }) }
func (c *ClientSession) SendDONE(p *DONE)             { c.s.send(p) }
func (c *ClientSession) OnEE(h func(*EE))             { c.s.on("EE", func(p any) { h(p.(*EE)) }) }
func (c *ClientSession) SendFL(p *FL)                 { c.s.send(p) }
func (c *ClientSession) OnHI(h func(*HI))             { c.s.on("HI", func(p any) { h(p.(*HI)) }) }
func (c *ClientSession) SendHP(p *HPToClient)         { c.s.send(p) }
func (c *ClientSession) OnHP(h func(*HPToServer))     { c.s.on("HP", func(p any) { h(p.(*HPToServer)) }) }
func (c *ClientSession) SendID(p *IDToClient)         { c.s.send(p) }
func (c *ClientSession) OnID(h func(*IDToServer))     { c.s.on("ID", func(p any) { h(p.(*IDToServer)) }) }
func (c *ClientSession) SendJD(p *JD)                 { c.s.send(p) }
func (c *ClientSession) SendKB(p *KB)                 { c.s.send(p) }
func (c *ClientSession) SendKK(p *KK)                 { c.s.send(p) }
func (c *ClientSession) SendLE(p *LE)                 { c.s.send(p) }
func (c *ClientSession) SendMC(p *MCToClient)         { c.s.send(p) }
func (c *ClientSession) OnMC(h func(*MCToServer))     { c.s.on("MC", func(p any) { h(p.(*MCToServer)) }) }
func (c *ClientSession) SendMS(p *MSToClient)         { c.s.send(p) }
func (c *ClientSession) OnMS(h func(*MSToServer))     { c.s.on("MS", func(p any) { h(p.(*MSToServer)) }) }
func (c *ClientSession) OnPE(h func(*PE))             { c.s.on("PE", func(p any) { h(p.(*PE)) }) }
func (c *ClientSession) SendPN(p *PN)                 { c.s.send(p) }
func (c *ClientSession) SendPR(p *PR)                 { c.s.send(p) }
func (c *ClientSession) SendPU(p *PU)                 { c.s.send(p) }
func (c *ClientSession) SendPV(p *PV)                 { c.s.send(p) }
func (c *ClientSession) SendRT(p *RTToClient)         { c.s.send(p) }
func (c *ClientSession) OnRT(h func(*RTToServer))     { c.s.on("RT", func(p any) { h(p.(*RTToServer)) }) }
func (c *ClientSession) SendSC(p *SC)                 { c.s.send(p) }
func (c *ClientSession) SendSI(p *SI)                 { c.s.send(p) }
func (c *ClientSession) SendSM(p *SM)                 { c.s.send(p) }
func (c *ClientSession) SendSP(p *SP)                 { c.s.send(p) }
func (c *ClientSession) SendVS_AUDIO(p *VS_AUDIO)     { c.s.send(p) }
func (c *ClientSession) SendVS_CAPS(p *VS_CAPS)       { c.s.send(p) }
func (c *ClientSession) OnVS_FRAME(h func(*VS_FRAME)) {
	c.s.on("VS_FRAME", func(p any) { h(p.(*VS_FRAME)) })
}
func (c *ClientSession) SendVS_JOIN(p *VS_JOINToClient)   { c.s.send(p) }
func (c *ClientSession) SendVS_LEAVE(p *VS_LEAVEToClient) { c.s.send(p) }
func (c *ClientSession) SendVS_PEERS(p *VS_PEERS)         { c.s.send(p) }
func (c *ClientSession) SendVS_SPEAK(p *VS_SPEAKToClient) { c.s.send(p) }
func (c *ClientSession) OnVS_SPEAK(h func(*VS_SPEAKToServer)) {
	c.s.on("VS_SPEAK", func(p any) { h(p.(*VS_SPEAKToServer)) })
}
func (c *ClientSession) SendZZ(p *ZZToClient)       { c.s.send(p) }
func (c *ClientSession) OnZZ(h func(*ZZToServer))   { c.s.on("ZZ", func(p any) { h(p.(*ZZToServer)) }) }
func (c *ClientSession) SendDecryptor(p *Decryptor) { c.s.send(p) }
