// Code generated by cmd/aolib-gen from spec. DO NOT EDIT.

package aolib

// Effect is MS screen-effect overlay request: effect name, misc folder, and sound, packed into one `name|folder|sound` wire slot. An all-empty value is the no-effect sentinel and encodes to an empty slot.
type Effect struct {
	Name   string `json:"name"`
	Folder string `json:"folder"`
	Sound  string `json:"sound"`
}

// Offset is Integer (x, y) screen-coordinate pair carried in MS offset / paired_offset slots.
type Offset struct {
	X int `json:"x"`
	Y int `json:"y"`
}
