// Code generated by cmd/aolib-gen from spec. DO NOT EDIT.

package aolib

func (s *ServerSession) OnARUP(h func(*ARUP))     { s.s.on("ARUP", func(p any) { h(p.(*ARUP)) }) }
func (s *ServerSession) OnASS(h func(*ASS))       { s.s.on("ASS", func(p any) { h(p.(*ASS)) }) }
func (s *ServerSession) OnAUTH(h func(*AUTH))     { s.s.on("AUTH", func(p any) { h(p.(*AUTH)) }) }
func (s *ServerSession) OnBB(h func(*BB))         { s.s.on("BB", func(p any) { h(p.(*BB)) }) }
func (s *ServerSession) OnBD(h func(*BD))         { s.s.on("BD", func(p any) { h(p.(*BD)) }) }
func (s *ServerSession) OnBN(h func(*BN))         { s.s.on("BN", func(p any) { h(p.(*BN)) }) }
func (s *ServerSession) SendCC(p *CC)             { s.s.send(p) }
func (s *ServerSession) SendCH(p *CH)             { s.s.send(p) }
func (s *ServerSession) OnCHECK(h func(*CHECK))   { s.s.on("CHECK", func(p any) { h(p.(*CHECK)) }) }
func (s *ServerSession) OnCI(h func(*CI))         { s.s.on("CI", func(p any) { h(p.(*CI)) }) }
func (s *ServerSession) OnCT(h func(*CTToClient)) { s.s.on("CT", func(p any) { h(p.(*CTToClient)) }) }
func (s *ServerSession) SendCT(p *CTToServer)     { s.s.send(p) }
func (s *ServerSession) OnCharsCheck(h func(*CharsCheck)) {
	s.s.on("CharsCheck", func(p any) { h(p.(*CharsCheck)) })
}
func (s *ServerSession) SendDE(p *DE)             { s.s.send(p) }
func (s *ServerSession) OnDONE(h func(*DONE))     { s.s.on("DONE", func(p any) { h(p.(*DONE)) }) }
func (s *ServerSession) SendEE(p *EE)             { s.s.send(p) }
func (s *ServerSession) OnEI(h func(*EI))         { s.s.on("EI", func(p any) { h(p.(*EI)) }) }
func (s *ServerSession) OnEM(h func(*EM))         { s.s.on("EM", func(p any) { h(p.(*EM)) }) }
func (s *ServerSession) OnFA(h func(*FA))         { s.s.on("FA", func(p any) { h(p.(*FA)) }) }
func (s *ServerSession) OnFL(h func(*FL))         { s.s.on("FL", func(p any) { h(p.(*FL)) }) }
func (s *ServerSession) OnFM(h func(*FM))         { s.s.on("FM", func(p any) { h(p.(*FM)) }) }
func (s *ServerSession) SendHI(p *HI)             { s.s.send(p) }
func (s *ServerSession) OnHP(h func(*HPToClient)) { s.s.on("HP", func(p any) { h(p.(*HPToClient)) }) }
func (s *ServerSession) SendHP(p *HPToServer)     { s.s.send(p) }
func (s *ServerSession) OnID(h func(*IDToClient)) { s.s.on("ID", func(p any) { h(p.(*IDToClient)) }) }
func (s *ServerSession) SendID(p *IDToServer)     { s.s.send(p) }
func (s *ServerSession) OnJD(h func(*JD))         { s.s.on("JD", func(p any) { h(p.(*JD)) }) }
func (s *ServerSession) OnKB(h func(*KB))         { s.s.on("KB", func(p any) { h(p.(*KB)) }) }
func (s *ServerSession) OnKK(h func(*KK))         { s.s.on("KK", func(p any) { h(p.(*KK)) }) }
func (s *ServerSession) OnLE(h func(*LE))         { s.s.on("LE", func(p any) { h(p.(*LE)) }) }
func (s *ServerSession) SendMA(p *MA)             { s.s.send(p) }
func (s *ServerSession) OnMC(h func(*MCToClient)) { s.s.on("MC", func(p any) { h(p.(*MCToClient)) }) }
func (s *ServerSession) SendMC(p *MCToServer)     { s.s.send(p) }
func (s *ServerSession) OnMS(h func(*MSToClient)) { s.s.on("MS", func(p any) { h(p.(*MSToClient)) }) }
func (s *ServerSession) SendMS(p *MSToServer)     { s.s.send(p) }
func (s *ServerSession) SendPE(p *PE)             { s.s.send(p) }
func (s *ServerSession) OnPN(h func(*PN))         { s.s.on("PN", func(p any) { h(p.(*PN)) }) }
func (s *ServerSession) OnPR(h func(*PR))         { s.s.on("PR", func(p any) { h(p.(*PR)) }) }
func (s *ServerSession) OnPU(h func(*PU))         { s.s.on("PU", func(p any) { h(p.(*PU)) }) }
func (s *ServerSession) OnPV(h func(*PV))         { s.s.on("PV", func(p any) { h(p.(*PV)) }) }
func (s *ServerSession) SendRC(p *RC)             { s.s.send(p) }
func (s *ServerSession) SendRD(p *RD)             { s.s.send(p) }
func (s *ServerSession) SendRM(p *RM)             { s.s.send(p) }
func (s *ServerSession) OnRMC(h func(*RMC))       { s.s.on("RMC", func(p any) { h(p.(*RMC)) }) }
func (s *ServerSession) OnRT(h func(*RTToClient)) { s.s.on("RT", func(p any) { h(p.(*RTToClient)) }) }
func (s *ServerSession) SendRT(p *RTToServer)     { s.s.send(p) }
func (s *ServerSession) OnSC(h func(*SC))         { s.s.on("SC", func(p any) { h(p.(*SC)) }) }
func (s *ServerSession) OnSI(h func(*SI))         { s.s.on("SI", func(p any) { h(p.(*SI)) }) }
func (s *ServerSession) OnSM(h func(*SM))         { s.s.on("SM", func(p any) { h(p.(*SM)) }) }
func (s *ServerSession) OnSP(h func(*SP))         { s.s.on("SP", func(p any) { h(p.(*SP)) }) }
func (s *ServerSession) OnTI(h func(*TI))         { s.s.on("TI", func(p any) { h(p.(*TI)) }) }
func (s *ServerSession) OnZZ(h func(*ZZToClient)) { s.s.on("ZZ", func(p any) { h(p.(*ZZToClient)) }) }
func (s *ServerSession) SendZZ(p *ZZToServer)     { s.s.send(p) }
func (s *ServerSession) SendAskchaa(p *Askchaa)   { s.s.send(p) }
func (s *ServerSession) OnDecryptor(h func(*Decryptor)) {
	s.s.on("decryptor", func(p any) { h(p.(*Decryptor)) })
}
